### ISSUE TITLE
Smtp using proxy server

### ISSUE THREAD

**Issue by Afonichev** [javaee/javamail#260]
How to send a message through a proxy server (proxyServer, proxyPort, proxyLogin, proxyPassword)?

**Comment by bshannon** [comment]
Filing issues isn't really the [right way to ask questions](https://javaee.github.io/javamail/#Help).  Try the [javamail@javaee.groups.io mailing list](https://javaee.groups.io/g/javamail).

The JavaMail FAQ has information about using [proxy servers](https://javaee.github.io/javamail/FAQ#proxy).  JavaMail 1.6 will also include direct support for HTTP proxy servers, but it doesn't support authentication.  If you really need to login to your proxy server, you may need to use one of the other alternatives such as [Corkscrew](http://en.wikipedia.org/wiki/Corkscrew_%28program%29).

**Comment by Afonichev** [comment]
This is very bad. Thank.
