### ISSUE TITLE
SSL (java.security.cert.CertPathValidatorException)

### ISSUE THREAD

**Issue by Rajeshr34** [javaee/javamail#261]
Using this IMAP: 
`imap://email:password@imap.mail.yahoo.com | [mail.imap.ssl.enable]`

Iam facing this issue:

`java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

Seems the problem in latest android OS 7.1.1 . is there any quick fix?

**Comment by bshannon** [comment]
Did you see this [JavaMail FAQ entry](https://javaee.github.io/javamail/FAQ#installcert)?

Most likely there's a firewall or anti-virus intercepting your request.

**Comment by bshannon** [comment]
No response from the submitter so I'm closing this.
