### ISSUE TITLE
maybe typo JavaMail-1.6-changes.txt

### ISSUE THREAD

**Issue by sis-yoshiday** [javaee/javamail#263]
https://github.com/javaee/javamail/blob/gh-pages/docs/JavaMail-1.6-changes.txt#L5

> (Updated August 28, 2017)

This date is future, is it some mistake ?
Sorry the little things, but I feel it strange.

**Comment by bshannon** [comment]
Ya, that was the expected release date for Java EE 8, which includes JavaMail 1.6.
But I needed to actually release JavaMail 1.6 earlier so that I could integrate the
final version into the Java EE 8 Reference Implementation.  Obviously I forgot to
update this date.  :-(

**Comment by sis-yoshiday** [comment]
I understand why it was. Thanks for explanation !
