### ISSUE TITLE
java.lang.ClassNotFoundException: javax.activation.DataSource

### ISSUE THREAD

**Issue by Horcrux7** [javaee/javamail#266]
With Java 9 we receive the follow exception. It work with Java 8. What is the recommended solution for it? Does we need to bundle the activation.jar again?

```
java.lang.ClassNotFoundException: javax.activation.DataSource
 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
```

**Comment by bshannon** [comment]
JDK 9 disables access to many of the javax.* APIs by default.
You need to add the command line option `--add-modules java.activation` to enable access to the javax.activation APIs.  (Note that there's no "x" in the module name.)

**Comment by Horcrux7** [comment]
The module java.activation is deprecated in Java 9 and is mark for remove in future versions: http://download.java.net/java/jdk9/docs/api/java.activation-summary.html

Do you plan a version without java.activation in the future?

**Comment by bshannon** [comment]
A standalone version of the JavaBeans Activation Framework version 1.2, the same version that's integrated into JDK 9, will be made available when JDK 9 is complete.  You can find this version on [GitHub](https://github.com/javaee/activation).  This will be usable with JDK 9 without the need for the `--add-modules` option, and will be usable with JDK 10 if the java.activation module is removed from JDK 10.

**Comment by jansohn** [comment]
@bshannon what is preventing you from already switching to the standalone JavaBeans Activation Framework version 1.2?
Java compatibility seems to be Java 5:

    $ javap.exe -verbose javax.activation-1.2.0\javax\activation\MimeType.class | findstr "major"
      major version: 49
