### ISSUE TITLE
Kenai bug reports no longer available

### ISSUE THREAD

**Issue by veita** [javaee/javamail#267]
The [Kenai](http://www.oracle.com/splash/kenai.com/decommissioning/index.html) bug tracker has been closed. Our documentation links that reference issues therein do not work anymore.

Is there a replacement for Kenai where the issues can be seen?

**Comment by bshannon** [comment]
Did you look in the same place you posted this issue?  They're all here!
They were migrated from the Kenai bugzilla.

The [IssueMap.txt](https://github.com/javaee/javamail/blob/master/doc/release/IssueMap.txt) file contains the mapping from Kenai issue numbers to GitHub issue numbers.

**Comment by veita** [comment]
Thank you very much! That's exactly what I needed.
