### ISSUE TITLE
Do I (still) need UTF-7?

### ISSUE THREAD

**Issue by raimi** [javaee/javamail#269]
Dear JavaMail-Team! Sorry for this strange issue, but it bugs me for years:

Years ago we put jutf7.jar from https://sourceforge.net/projects/jutf7/ into our application, because while reading email sometimes an java.io.UnsupportedEncodingException: unicode-1-1-utf-7  was thrown.

So we did, what everyone else does:
 * https://stackoverflow.com/questions/19861987/java-io-unsupportedencodingexception-unicode-1-1-utf-7
 * https://confluence.atlassian.com/jirakb/parsing-utf-7-email-messages-643137684.html

The problem is: jutf7.jar has to be put in a priviledged place: The Tomcat "endorsed" directory or $JAVA_HOME/jre/lib/ - which is a maintenance and documentation pain. Also, there is no hope of the JDK itself ever supporting this encoding itself (there a dismissed bug reports).

The question is: Is all this still neccessary? Is there a fix in JavaMail that made this problem disappear? I assume JavaMail itself can handle UTF-7 internally as it is required for IMAP. Why did that encoding ever creep into my application level? From what I can tell, it was Exchange and/or Outlook involved (what else...).

Or in other words: Can I somehow tell JavaMail to use jutf7.jar from an unpriviledged location?
Thanks and sorry for the confusion...

**Comment by bshannon** [comment]
IMAP uses a modified version of UTF-7.

JavaMail depends on the JDK to do all the charset encoding/decoding.  I've tried to convince
the JDK group to add UTF-7 support, but as you note they're not interested in doing that.
It's used very rarely.

I'm not an expert in how the JDK finds charset providers and what the restrictions are.
If it's requiring them to be in a privileged location that's probably for security reasons.
I don't think there's anything JavaMail can do to override that.  I'm definitely not going
to add a special case to JavaMail just for this charset.

**Comment by phax** [comment]
To my knowledge external charsets are loaded via the "regular" SPI mechanism (using `java.nio.charset.spi.CharsetProvider`). So to my knowledge this can be bundled with the respective application and does not need to be in endorsed folder.

**Comment by bshannon** [comment]
Since this is really a JDK issue, I'm closing this issue.  I don't think there's anything JavaMail can do to help with this, other than special-casing this throughout the code, which I'm not going to do.  Sorry.
