### ISSUE TITLE
Does the IdleManager handle temporary disconnects?

### ISSUE THREAD

**Issue by mmoehring** [javaee/javamail#272]
Hello there,

I am using JavaMail 1.5.6 and have set up an IdleManager with a MessageCountListener for watching the Inbox.
Does the IdleManger handle temporary disconnect of the underlying Store / IMAPFolder automatically or do I have to handle them manually?
Are there any best practices or hints regarding such retry/reconnection attempts?

TIA

**Comment by bshannon** [comment]
A better place to ask questions is the [JavaMail mailing list](https://javaee.groups.io/g/javamail) or javamail_ww@oracle.com.

> Does the IdleManger handle temporary disconnect of the underlying Store / IMAPFolder automatically or do I have to handle them manually?

IdleManager doesn't do anything to handle disconnects.  If the server disconnects, you have to detect that and reconnect.

> Are there any best practices or hints regarding such retry/reconnection attempts?

It depends a lot on your application and your mail server.

Mail servers don't want you to be connected for long periods of time if you're not doing anything.  if your user interface can detect whether the user is not actively using the mail server, it should probably ignore the disconnects until the user again starts to use the mail server.
