### ISSUE TITLE
java.lang.ClassNotFoundException: com.sun.mail.smtp.SMTPSaslAuthenticator JavaMail Android

### ISSUE THREAD

**Issue by mosamabinomar** [javaee/javamail#277]
```
Properties props=System.getProperties();
props.put("mail.smtp.starttls.enable", "true");
props.put("mail.smtp.starttls.required", "true");
props.put("mail.smtp.sasl.enable", "true");
props.put("mail.smtp.sasl.mechanisms", "XOAUTH2");
Session session = Session.getInstance(props);
session.setDebug(true);

Message message1 = new MimeMessage(MailsSharedData.getSession());
message1.setFrom(new InternetAddress(ConfigManager.getEmail()));
message1.setRecipient(Message.RecipientType.TO, new InternetAddress(to));
message1.setSubject(subject);
message1.setSentDate(new Date());
message1.setText(message);
session.getTransport().connect("smtp.gmail.com",587,ConfigManager.getEmail(), Constants.ACCESS_TOKEN);
session.getTransport().sendMessage(message1,message1.getAllRecipients());
```

**Comment by bshannon** [comment]
Are you sure your build is using the Android version of JavaMail, as described [here](https://javaee.github.io/javamail/Android)?

Note that in your code above you're using two different Transport objects - one of which you're connecting and then thrown away, the other of which you're trying to send a message without connecting.

**Comment by mosamabinomar** [comment]
Thanks solved! using
```
final URLName unusedUrlName = null;

SMTPTransport transport = new SMTPTransport(session, unusedUrlName);

transport.connect("smtp.gmail.com",465,ConfigManager.getEmail(), Constants.ACCESS_TOKEN);
```

**Comment by bshannon** [comment]
As described on the [JavaMail Android page](https://javaee.github.io/javamail/Android) and the [JavaMail OAuth2 page](https://javaee.github.io/javamail/OAuth2), don't enable SASL.

**Comment by bshannon** [comment]
In general, you should not need to instantiate the SMTPTransport class yourself.  Session.getTransport("smtp") should be sufficient.  If you fix the other problems pointed out above it should work much better.
