### ISSUE TITLE
BODYSTRUCTURE Parser fails on specific IMAP Server response

### ISSUE THREAD

**Issue by DJGummikuh** [javaee/javamail#278]
Hey!
I'm using Javamail (1.5.4, however the issue still persists in 1.6.0) and am running into issues when trying to download a message from an Exchange 2016 server.
After issueing the command
`A6 FETCH 1 (BODYSTRUCTURE)`
the server responds with
`* 1 FETCH (BODYSTRUCTURE (("text" "plain" ("charset" "us-ascii") NIL NIL "7bit" 21 0 NIL ("inline" NIL) NIL NIL)("application" "octet-stream" ("name" "private.txt") NIL NIL "base64" 690 NIL ("attachment" ("filename" "private.txt")) NIL NIL) "mixed" ("boundary" "----=_Part_0_-1731707885.1504253815584") "S/MIME Encrypted Message" NIL))`

Which javamail consecutively causes to throw a parse Exception:
`DEBUG IMAP: ignoring bad response, THROW: 
com.sun.mail.iap.ParsingException: BODYSTRUCTURE parse error: multipart/mixed: bad multipart disposition, b 34
	at com.sun.mail.imap.protocol.BODYSTRUCTURE.<init>(BODYSTRUCTURE.java:166)
	at com.sun.mail.imap.protocol.FetchResponse.parseItem(FetchResponse.java:260)
	at com.sun.mail.imap.protocol.FetchResponse.parse(FetchResponse.java:215)
	at com.sun.mail.imap.protocol.FetchResponse.<init>(FetchResponse.java:96)
	at com.sun.mail.imap.protocol.IMAPProtocol.readResponse(IMAPProtocol.java:350)
	at com.sun.mail.iap.Protocol.command(Protocol.java:357)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetch(IMAPProtocol.java:1937)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetch(IMAPProtocol.java:1929)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetchBodyStructure(IMAPProtocol.java:1504)
	at com.sun.mail.imap.IMAPMessage.loadBODYSTRUCTURE(IMAPMessage.java:1461)
	at com.sun.mail.imap.IMAPMessage.getContentType(IMAPMessage.java:555)
	3< 3< 3< 3< 3< 3<`

Unfortunately I do not know whether this parse error is because Exchange 2016 is violating the structure of BODYSTRUCTURE (which would impose our customer has to fix his mailserver) or if the BODYSTRUCTURE is actually syntactically correct and Javamail has an issue.

The Issue is the "S/MIME Encrypted Message" section of the BODYSTRUCTURE, the parser expects either a '(' or a 'N'/'n' but gets the " (ASCII Code 34).

**Comment by bshannon** [comment]
The server is broken, please report this bug to Microsoft.

The IMAP protocol syntax describing this part of the response is:
```
body-ext-mpart  = body-fld-param [SP body-fld-dsp [SP body-fld-lang
                  [SP body-fld-loc *(SP body-extension)]]]
body-fld-dsp    = "(" string SP body-fld-param ")" / nil
```
The parenthesized "boundary" part matches `body-fld-param`.  The following text should
match `body-fld-dsp`, which must start with either a left parenthesis or be the constant `NIL`.

Can you post the MIME content of the message so I can see what MIME headers
caused this response from the server?

JavaMail has quite a few workarounds for bugs in Exchange.  I'll look into adding another
to cover this case, but it would be **so** much better if Microsoft would fix Exchange.

**Comment by DJGummikuh** [comment]
Hey! Thanks for your response. I have ONE MIME Mail but unfortunately not one of the mails I can verify that they created this communication pattern (yet). Once I have it I will send it to you. The MIME Mail that I DO have (though, as said, I cannot verify that this mail would create the exact same error) has the "S/MIME Encrypted Mail" String only in the "Content-Description:" header.

**Comment by bshannon** [comment]
Content-Disposition and Content-Description are not the same thing at all,
so if the server is confusing the two it's definitely a bug.  Content-Description
information can appear in the IMAP response associated with each individual
message part, but where it's appearing here is associated with the multipart
as a whole.

**Comment by DJGummikuh** [comment]
I haven't forgotten you, still trying hard to retrieve a mail that I can actually prove for that it causes the exception in javamail.

**Comment by DJGummikuh** [comment]
I haven't forgotten you, still trying hard to retrieve a mail that I can actually prove for that it causes the exception in javamail. I'll update that issue the moment I get the response from our customer.

**Comment by mkioussi** [comment]
Hi,
what exactly is meant with the "mail server is broken"? What should be done on the mail server to fix this problem?
I have come across this error and similar ones reported from the JavaMail library, and the answer always is "there is a problem on the mail server". I cannot get more info on this, so I would appreciate it if you elaborated a little on the subject.

**Comment by bshannon** [comment]
I tried to explain it in the posts above.  You have to be able to read BNF to understand the
syntax requirements for an IMAP message.  The IMAP server can't just send anything that
it wants.  It has to conform to the IMAP message syntax requirements.  As explained in the
[JavaMail FAQ](https://javaee.github.io/javamail/FAQ#imapserverbug), many IMAP clients don't use very much of the IMAP protocol, and so never
run into these bugs in the IMAP server.

The specific issue reported here is explained above.  If you have other specific instances of
this problem, I can explain what error the IMAP server is making.  Fixing the IMAP server is
a problem for the developer of the IMAP server, not a user of the IMAP server.

**Comment by DJGummikuh** [comment]
Hey. My customer is a bit difficult to work with (also, the person responsible was on sick leave) so I still do not have a 100% proof that it's indeed the Content-Description that is mis-used as Content-Disposition but so far the files I got also do not proof the opposite. I'll keep you updated. I'm perfectly d'accord with you that this appears to be a mailserver issue, however I believe that hell freezes over before Microsoft suddendly starts adhering to standards they did not set themselves... :-(

**Comment by DJGummikuh** [comment]
I talked to the customer the other day and he gave me the proof I asked for. Here is the data (I substituted some obvious customer related data such as sender and recipient e-mail)

=====================
Fetching the Envelope
=====================
A14 FETCH 9 (ENVELOPE INTERNALDATE RFC822.SIZE)
* 9 FETCH (ENVELOPE ("Sun, 15 Oct 2017 11:57:00 +0200" "MSCONS_TL_12345.txt [secure]" ((NIL NIL "sender" "email.com")) NIL NIL ((NIL NIL "recipient" "email.com")) ((NIL NIL "cc" "email.com")) NIL NIL "<Message ID>") INTERNALDATE "15-Oct-2017 11:57:14 +0200" RFC822.SIZE 145348)


=====================
Fetching the body structure
=====================
A44 FETCH 9 (FLAGS)
* 9 FETCH (FLAGS ())
A44 OK FETCH completed.
A45 FETCH 9 (UID)
* 9 FETCH (UID 110568)
A45 OK FETCH completed.
A46 FETCH 9 (BODYSTRUCTURE)
* 9 FETCH (BODYSTRUCTURE (("text" "plain" ("charset" "us-ascii") NIL NIL "7bit" 0 0 NIL NIL NIL NIL)("application" "octet-stream" ("name" "MSCONS_TL_9907305000001_9906622000009_20171015_1728800281242.txt") NIL NIL "base64" 171724 NIL ("attachment" ("filename" "MSCONS_TL_9907305000001_9906622000009_20171015_1728800281242.txt")) NIL NIL) "mixed" ("boundary" "----=_Part_694_566091238.1508061421046") "S/MIME Encrypted Message" NIL))
DEBUG IMAP: ignoring bad response, THROW: 
com.sun.mail.iap.ParsingException: BODYSTRUCTURE parse error: multipart/mixed: bad multipart disposition, b 34
	at com.sun.mail.imap.protocol.BODYSTRUCTURE.<init>(BODYSTRUCTURE.java:166)
	at com.sun.mail.imap.protocol.FetchResponse.parseItem(FetchResponse.java:260)
	at com.sun.mail.imap.protocol.FetchResponse.parse(FetchResponse.java:215)
	at com.sun.mail.imap.protocol.FetchResponse.<init>(FetchResponse.java:96)
	at com.sun.mail.imap.protocol.IMAPProtocol.readResponse(IMAPProtocol.java:350)
	at com.sun.mail.iap.Protocol.command(Protocol.java:357)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetch(IMAPProtocol.java:1937)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetch(IMAPProtocol.java:1929)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetchBodyStructure(IMAPProtocol.java:1504)
	at com.sun.mail.imap.IMAPMessage.loadBODYSTRUCTURE(IMAPMessage.java:1461)
	at com.sun.mail.imap.IMAPMessage.getContentType(IMAPMessage.java:555)
	at de.kisters.kidsm.auto.location.MailLocation.extractMailInfo(MailLocation.java:1704)
	at de.kisters.kidsm.auto.location.MailLocation.retrieveItemsFiltered(MailLocation.java:1948)
	at de.kisters.kidsm.auto.location.LocationBase.retrieveItemsFiltered(LocationBase.java:472)
	at de.kisters.kidsm.auto.location.LocationBase.transferItemsFilteredTo(LocationBase.java:626)
	at de.kisters.kidsm.auto.job.DistributionJob.executeTask(DistributionJob.java:82)
	at de.kisters.kidsm.auto.job.JobBase.run(JobBase.java:286)
A46 OK FETCH completed.
DEBUG IMAP: IMAPProtocol noop
A47 NOOP
A47 OK NOOP completed.


=====================
The accompanying e-mail
=====================
Received: from COM06.radeland.nea-hamburg.de (194.0.149.19) by
 COM05.radeland.nea-hamburg.de (194.0.149.18) with Microsoft SMTP Server
 (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P256) id
 15.1.845.34 via Mailbox Transport; Sun, 15 Oct 2017 11:57:14 +0200
Received: from COM03.radeland.nea-hamburg.de (194.0.149.20) by
 COM06.radeland.nea-hamburg.de (194.0.149.19) with Microsoft SMTP Server
 (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P256) id
 15.1.845.34; Sun, 15 Oct 2017 11:57:14 +0200
Received: from mailcrypt02.zentral.eon-hanse-waerme.com (194.0.149.15) by
 COM03.radeland.nea-hamburg.de (194.0.149.41) with Microsoft SMTP Server (TLS)
 id 15.0.1130.7 via Frontend Transport; Sun, 15 Oct 2017 11:57:13 +0200
Received: from mailin1.eon-hanse-waerme.com (mailin1.eon-hanse-waerme.com [194.0.149.234])
	by mailcrypt02.zentral.eon-hanse-waerme.com (Postfix) with ESMTP
	for <recipient@email.com>; Sun, 15 Oct 2017 11:57:07 +0200 (CEST)
X-AuditID: c20095ea-a4bff70000001058-06-59e330f0532d
Received: from mail-gw01.service-plus-gmbh.de (mail-gw01.service-plus-gmbh.de [89.246.253.235])
	(using TLS with cipher IDEA-CBC-SHA (112/128 bits))
	(Client did not present a certificate)
	by mailin1.eon-hanse-waerme.com (Mail-Gateway) with SMTP id C5.CA.04184.1F033E95; Sun, 15 Oct 2017 11:57:07 +0200 (CEST)
X-IronPort-AV: E=Sophos;i="5.43,368,1503352800"; 
   d="p7m'?scan'208";a="2002517"
X-Attachment-filename: smime.p7m
Received: from unknown (HELO progov-srv01.service-plus-gmbh.de) ([172.29.14.36])
  by mail-gw01.service-plus-gmbh.de with ESMTP/TLS/DHE-RSA-AES256-SHA; 15 Oct 2017 11:57:04 +0200
Received: from progov-srv01.service-plus-gmbh.de (localhost [127.0.0.1])
	by progov-srv01.service-plus-gmbh.de (Postfix) with ESMTP id 5B00B4411D0
	for <recipient@email.com>; Sun, 15 Oct 2017 11:57:03 +0200 (CEST)
Received: from NTSTP-SRV003.service-plus-gmbh.de (ntstp-srv003.service-plus-gmbh.de [172.29.18.131])
	by progov-srv01.service-plus-gmbh.de (Postfix) with ESMTP id 28DA44411D0
	for <recipient@email.com>; Sun, 15 Oct 2017 11:57:00 +0200 (CEST)
From: <sender@email.com>
To: <recipient@email.com>
Message-ID: <Message ID>
Subject: MSCONS_TL_12345.txt [secure]
Date: Sun, 15 Oct 2017 11:57:00 +0200
CC: <cc@email.com>
x-pg-smime: signature; key="RSA;2048"; digest-algorithm=SHA256; 
	signature-algorithm=SHA256WITHRSA
x-pg-smime: encryption; key="RSA;2048"; content-algorithm="AES-192/CBC"; 
	key-algorithm=RSA
x-signed-by: progov
Content-Description: S/MIME Encrypted Message
x-encrypted-by: ProGOV
Authentication-Results: symauth.hansewerk-natur.com; spf=neutral
X-Brightmail-Tracker: H4sIAAAAAAAAA+NgFprCJsWRWlGSWpSXmKPExsUS+e3va93PBo8jDX7OlrJ417+LyYHR48Ln
	3UwBjFFcNimpOZllqUX6dglcGWunT2ItaHvAV/HwmnMD44X1fF2MnBwSAiYSB/b/Ye9i5OIQ
	EtjJJDF/wgwWiESwxI3PWxkhbAWJzrOL2CCKNjNKLP+1Dsp5xyhx4v9PJgini0ni54JOZpAW
	NgFFiY7Xh9hAbBEBPYmV356BjeIV8JPYem4pmC0s4ClxZd0JNoi4oMTJmU/AVjMLBEp8eTaV
	CcRmEdCR2HJ+DxNEXFXi1pZ37BAnpUgsvvEO6tRYie4ft6BOFZa41rGLEaLeVGLbt6tQMxUl
	pnQ/ZIewdSUm3d7NBlEvJvHlTg+YzSjgIHF21hXGCYzis5CcNAvJSbOQjJ2FZOwsJGMXMLKu
	YpTJTczMycwz1EvNz9PNSMwrTtUtT0wtyk3VS87P3cQIjLhDDFNf7WA8edDpEKM0B6MUZ2pe
	clFlQUlqihIPbyswPoVYE8uKK3MPMUpyMCmJ8p5rfRgpxJeUn1KZkVicEV9UmpNafIhRBWjr
	ow2rLzBKseTl56UqifAqcwO18qYkVlalFuXDlElzsCiJ8xbcXhosJJCeWJKanZpakFoEk2Xi
	YD/EKMPBoSTBu0sfqFuwKDU9tSItM6cEWQ0niOA6xCjBwQO05pQeyJrigsTc4sx0iKJTjIpS
	4ryNIBMEQBIZpXlwA2Ap9RKjrJQwLyMDA4MQD9AFuZklqPKPGBleMYpzMCoJ86qCwoAnM68E
	bsEroN1MQLvfRTwA2V2SiJCSamA0kuxiW+Gyb7VJyerJwZNbp1bw87CLi2/dZ3L292phVvMV
	a5PFpvHq5F86/5w/Mz9s76dza089EJt7vOt4nNxH5ZvL42wEres/Pd65afvZVZN4rzt/uzVn
	facMg5Xkuqp8zxd58z05vV/++fKw3/T3ovPa/LmKwlZVBtFr4s5XKyt8f9rvt+W0EktxRqKh
	FnNRcSIAL26ngacDAAA=
Content-Type: multipart/mixed;
	boundary="----=_Part_694_566091238.1508061421046"
Return-Path: sender@email.com
X-MS-Exchange-Organization-Network-Message-Id: 2d7789d5-6494-42a2-860b-08d513b31c76
X-MS-Exchange-Organization-AVStamp-Enterprise: 1.0
X-MS-Exchange-Organization-AuthSource: COM03.radeland.nea-hamburg.de
X-MS-Exchange-Organization-AuthAs: Anonymous
X-MS-Exchange-Transport-EndToEndLatency: 00:00:00.6664320
MIME-Version: 1.0

------=_Part_694_566091238.1508061421046
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: 7bit


------=_Part_694_566091238.1508061421046
Content-Type: application/octet-stream;
	name="MSCONS_TL_12345.txt"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename="MSCONS_TL_12345.txt"

3< 3< 3< Snipped, not relevant since javamail already crashes while requesting the BODYSTRUCTURE. >3 >3 >3
------=_Part_694_566091238.1508061421046--

**Comment by DJGummikuh** [comment]
One addition I only found out after placing this comment: 
Even though the mail sports this nice header:
Content-Description: S/MIME Encrypted Message
It actually is a plain MIME Message as there is an intermediary layer (before the mail even reaches outlook) that decrypts the mail...

**Comment by bshannon** [comment]
This very definitely is a bug in Exchange and you absolutely should report it.
Perhaps they already have a patch that fixes it?  If you get any information
from Microsoft, please let me know.  In the mean time I'll try to add yet another
workaround for this Exchange bug, although I have no idea what it thinks it's
doing here.  In particular, what does the NIL after this string represent?

**Comment by DJGummikuh** [comment]
I asked the customer to file a bug / check for a possibly already existing hotpatch from Microsoft. I will come back to him with your evaluation to further my point. Regarding the NIL I haven't the faintest, at least in all BODYSTRUCTURE Messages we captured the value directly behind the string was always NIL. Maybe it's as simple as Exchange messing up Content-Disposition and Content-Description when searching for tags? I mean they both share a rather large portion of their name (Content-D) which might have slipped by some over-worked Exchange-developer who thought he'd found a parsing shortcut here? :-)

**Comment by bshannon** [comment]
I pushed a 1.6.1-SNAPSHOT release with a workaround for this Exchange bug
to the maven.java.net repository.  If you get a chance to test it, let me know
if it works for you.

**Comment by DJGummikuh** [comment]
I just delivered a patch including your Snapshot to the customer for verification, the mails can now be downloaded from the Exchange server!

I owe you one!

**Comment by DJGummikuh** [comment]
@bshannon when will 1.6.1 be released? Is there any fixed release schedule or do you do it when time seems right? Just asking to be able to plan my releases better.
