### ISSUE TITLE
Support compress for multi-threaded use

### ISSUE THREAD

**Issue by nvsnvikram** [javaee/javamail#279]
java.util.zip Deflater & Inflater classes are using native zlib implementation and acquire thread level locks. These become a bottleneck if the imap client has to be used on a server to support multiple clients. Based on the current implementation, can you detail the solutions?

**Comment by bshannon** [comment]
Seems like a problem for the JDK to solve in its java.util.zip classes.
If there are other implementations of these same algorithms, let me know.
And let the JDK team know so they can replace theirs.

Have you actually seen this become a bottleneck in practice?

**Comment by nvsnvikram** [comment]
We are trying to use compress extension on our server and found the thread level locks when reviewing the code. Based on our experience dealing with other backend servers & apache http client, I/O with locks would become a problem with multiple imap client instances. We currently create imap client instances in 1000s.

Apache common compress seems to support DEFLATE algorithm for decompression: http://commons.apache.org/proper/commons-compress/examples.html. JZlib seems to support zlib compression and decompression: https://github.com/ymnk/jzlib.

**Comment by bshannon** [comment]
Apache Commons Compress [claims](http://commons.apache.org/proper/commons-compress/examples.html#DEFLATE) that it just uses java.util.zip.

JZlib might form the basis of a viable replacement, but since this is really a JDK problem
that's where it should be fixed.

At most I might consider adding a property that would allow you to select your own subclasses
that extend Deflater and Inflater.  This would allow you to provide your own implementation
based on JZlib, for example.

**Comment by nvsnvikram** [comment]
Agree that JDK should fix the Zlib implementation. Can you add properties for selecting Inflater and Deflater? We will try to switch with JZlib and see if that performs well.

**Comment by bshannon** [comment]
I asked the JDK team and they claim there should be no problems in this area.
Can you point me to the exact thread level locks that you believe cause a problem?

**Comment by nvsnvikram** [comment]
Thread level locks are in java.util.zip Inflater & Deflater but those seem to be for acquiring a reference to native ZStream object. Since imap client uses new instances of Inflater & Deflater, there is only one client locking on a single ZStream object. Thanks for your help.
