### ISSUE TITLE
Add Maven code example

### ISSUE THREAD

**Issue by feinstein** [javaee/javamail#281]
I makes A LOT easier to just copy and paste a maven dependency XML, like most open source projects provide, such as Dagger: https://github.com/google/dagger#maven and Log4j2: https://logging.apache.org/log4j/2.x/maven-artifacts.html.

So please, provide a simple copy/paste maven XML in the [main website](https://javaee.github.io/javamail/).

**Comment by bshannon** [comment]
I figured anyone using Maven would already know how to create a dependency entry
using the groupId and artifactId.  But you're right, lots of developers only know how
to copy and paste, so I've added a small example.
