### ISSUE TITLE
`Address` can not be parsed when it contains non-ASCII characters

### ISSUE THREAD

**Issue by Ray-Eldath** [javaee/javamail#284]
`Address.toString()`always returns:
```
Twitter <info@twitter.com>
```
for ASCII characters.

**But** when `Address` contains non-ASCII characters, it returns: 
```
=?UTF-8?Q?InfoQ=E4=B8=AD=E6=96=87=E7=AB=99?= <InfoQChina@infoq.geekbang.org>
```
It can be fixed with [Apache Commons Codec](http://mvnrepository.com/artifact/commons-codec/commons-codec) with codes below: 
```Java
public static String decode(String input) throws DecoderException {
	if (!(input.startsWith("=?") && input.endsWith("?=")))
		return input;
	String[] split = input.substring(2, input.length() - 2).split("\\?");
	Charset charset = Charset.forName(split[0]);
	char encoding = split[1].charAt(0);
	String data = split[2];
	return new String(
			encoding == 'Q' ?
			QuotedPrintableCodec.decodeQuotedPrintable(data.getBytes(charset)) : 
					Base64.getDecoder().decode(data.getBytes(charset)));
}
```

**Comment by bshannon** [comment]
Are you complaining that [InternetAddress.toString](https://javaee.github.io/javamail/docs/api/javax/mail/internet/InternetAddress.html#toString--) does exactly what it's specified to do:

> Convert this address into a RFC 822 / RFC 2047 encoded address. The resulting string contains only US-ASCII characters, and hence is mail-safe.

Maybe what you want is [InternetAddress.toUnicodeString](https://javaee.github.io/javamail/docs/api/javax/mail/internet/InternetAddress.html#toUnicodeString--)?

> Returns a properly formatted address (RFC 822 syntax) of Unicode characters.

**Comment by Ray-Eldath** [comment]
`Message.getFrom` returns `Address[]`...
For every `Address` in the array, could it be cast to `InternetAddress`?

**Comment by bshannon** [comment]
Yes, as long as you're using IMAP or POP3, you'll really be dealing with MimeMessage objects,
and can cast the Address objects to InternetAddress objects.
