### ISSUE TITLE
[trival] Remove new lines at the end of log messages

### ISSUE THREAD

**Issue by PascalSchumacher** [javaee/javamail#288]
Trival, but it would be nice if the new lines at the end of log messages were removed, as these lead to blank lines in the log.

e.g.:
https://github.com/javaee/javamail/blob/dca34da088a374636dcb8671df03019b904cd72d/mail/src/main/java/com/sun/mail/smtp/SMTPTransport.java#L2189

results in

```
com.sun.mail.smtp - connected to host "10.33.444.55", port: 25

javax.activation - MailcapCommandMap: createDataContentHandler for multipart/related
```

**Comment by bshannon** [comment]
I fixed those.  Let me know if you find any others.

**Comment by PascalSchumacher** [comment]
Thanks!
