### ISSUE TITLE
API changes review for Sun JavaMail API

### ISSUE THREAD

**Issue by lvc** [javaee/javamail#290]
The review of API changes for the Sun JavaMail API library since 1.4.4 version: https://abi-laboratory.pro/java/tracker/timeline/javax.mail/

The report is updated 3 times a week. Hope it will be helpful for users and maintainers of the library.

The report is generated by the https://github.com/lvc/japi-tracker tool for jars at http://central.maven.org/maven2/com/sun/mail/javax.mail/ according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.

![javax mail-2](https://user-images.githubusercontent.com/1517837/31983494-2451d52e-b966-11e7-9c94-4183444af73d.png)

![javax mail-1](https://user-images.githubusercontent.com/1517837/31983495-24706e08-b966-11e7-927a-7217cf5ce953.png)

**Comment by bshannon** [comment]
Thanks for the information, but I don't understand why this was filed as an issue.
Informative messages should be sent to the [mailing list](https://javaee.groups.io/g/javamail).
