### ISSUE TITLE
HTTP proxy support needs to use HTTP/1.1

### ISSUE THREAD

**Issue by SteveOswald** [javaee/javamail#296]
We're currently having troubles using a HTTP proxy.

If I telnet to our SMTP server using Putty, everything works fine. But, if I telnet to the proxy server an manually type "CONNECT mailserver.example:25 HTTP/1.0" and hit enter twice, the connection gets established, but the response is empty for some reasons. If I send "NOOP" once to the SMTP server, nothing will change. But if I send "NOOP" twice it responses with:

200 mailserver.example ESMTP
250 2.0.0 Ok
250 2.0.0 Ok

From this point, the connections works fine and I can send the SMTP server any command and it responses immediately. Maybe the proxy server is some kind of missconfigured, but we can't change the config on this machine.

If we configure the proxy server in JavaMail, the application does not respond. I don't know the reason why. If enabled  the logging and turned the loglevel to "FINEST" and got the following log:

Nov 24, 2017 5:56:03 PM com.sun.mail.smtp.SMTPTransport protocolConnect
FEIN: useEhlo true, useAuth true
Nov 24, 2017 5:56:03 PM com.sun.mail.smtp.SMTPTransport openServer
FEIN: trying to connect to host "mailserver.example", port 25, isSSL false
Nov 24, 2017 5:56:03 PM com.sun.mail.util.SocketFetcher getSocket
FEINER: getSocket, host mailserver.example, port 25, prefix mail.smtp, useSSL false
Nov 24, 2017 5:56:03 PM com.sun.mail.util.SocketFetcher createSocket
AM FEINSTEN: create socket: prefix mail.smtp, localaddr null, localport 0, host mailserver.example, port 25, connection timeout -1, timeout -1, socket factory null, useSSL false
Nov 24, 2017 5:56:03 PM com.sun.mail.util.SocketFetcher createSocket
FEINER: web proxy host proxyserver.example, port 8080
Nov 24, 2017 5:56:03 PM com.sun.mail.util.SocketFetcher createSocket
AM FEINSTEN: connecting...
Nov 24, 2017 5:56:03 PM com.sun.mail.util.SocketFetcher proxyConnect
FEIN: connecting through proxy proxyserver.example:8080 to mailserver.example:25
Nov 24, 2017 5:56:03 PM com.sun.mail.util.SocketFetcher proxyConnect
AM FEINSTEN: HTTP/1.1 200 Connection Established
Nov 24, 2017 5:56:03 PM com.sun.mail.util.SocketFetcher proxyConnect
AM FEINSTEN: Proxy-Agent: IWSS
Nov 24, 2017 5:56:03 PM com.sun.mail.util.SocketFetcher proxyConnect
AM FEINSTEN: Date: Fri, 24 Nov 2017 16:32:51 GMT
Nov 24, 2017 5:56:03 PM com.sun.mail.util.SocketFetcher proxyConnect
AM FEINSTEN: 
Nov 24, 2017 5:56:03 PM com.sun.mail.util.SocketFetcher createSocket
AM FEINSTEN: success!

Maybe it is possible to try to send the server the "NOOP" command 5 times, till it responses otherwise close the connection?

Best regards,
Steve

**Comment by bshannon** [comment]
What operating system are you using?  Are you running any sort of anti-virus software or local firewall software?

Can you try using the connect program, as described in the [JavaMail FAQ](https://javaee.github.io/javamail/FAQ#proxy)?  There's more information about using the connect program in the [JavaMail forum](https://community.oracle.com/thread/4095362).

I'd like to understand whether it's actually a bug in your proxy server before considering any kludges to JavaMail itself to work around the bug.

**Comment by SteveOswald** [comment]
Hi Bill,

I did a little research and had a look at how Putty does connecting through a HTTP proxy (because everything works fine in Putty). Putty is adding a "Host" header after the CONNECT command. So it should be:

CONNECT <host>:<port> HTTP/1.1
Host: <host>:<port>
<blank line>

It's also easy to do proxy authorization with the corresponding "Proxy-Authorization" header. I've tested this in squid and everything works as expected. Sadly I can't test it at the customer side (where the occurred). I'm sure the proxy server at the customer side isn't the best (but we can't change this fact).

The protocol with authorization should look like:

CONNECT <host>:<port> HTTP/1.1
Host: <host>:<port>
Proxy-Authorization: Basic base64(<username>:<password>)
<blank line>

I'm not the best Java programmer (I'm more familiar with C#), but I wrote some piece of code that you may can use.

Best regards,
Steve

[proxyConnect.zip](https://github.com/javaee/javamail/files/1509560/proxyConnect.zip)

**Comment by bshannon** [comment]
Exactly what proxy server is the customer using?  Can you test a fix at the customer's site?

JavaMail is using HTTP/1.0 to talk to the proxy server.  HTTP/1.0 does not require a Host: header.
Does the customer's proxy server only support HTTP/1.1?

**Comment by SteveOswald** [comment]
Hi Bill,

the customer is using the "Trend Micro InterScan Web Security Suite".

You are right, there even isn't a "Host" header in HTTP/1.0, but in fact JavaMail is already using HTTP/1.1. There isn't a "CONNECT" method defined in HTTP/1.0 (RFC 1945). The "CONNECT" method is defined since HTTP/1.1 (RFC 2616) and because JavaMail uses the "CONNECT" method from HTTP/1.1 there must be a "Host" header.

Quote from RFC 2616 (HTTP/1.1):
> A client MUST include a Host header field in all HTTP/1.1 request Messages .

So I think the code must be changed, to get the excepted behavior (wich is the way the HTTP/1.1 protocol seems to work).

I'll test it at the customer's site tomorrow, but I think there shouldn't be any problems.

Best regards,
Steve

**Comment by bshannon** [comment]
Hmmm...  Yes, it looks like you're right!

I'll fix it and push out a SNAPSHOT release ASAP.

**Comment by bshannon** [comment]
I've pushed a SNAPSHOT release.  Information on how to access it is [here](https://javaee.github.io/javamail/#Development_Releases).
Let me know if it solves your problem.
