### ISSUE TITLE
Folder.search not correctly

### ISSUE THREAD

**Issue by rubysuki** [javaee/javamail#304]
I need to develop Android Mail Application using JavaMail.
I connected to imap server of Gmail.
After that, i called getFolder by method  : store.getFolder("inbox");
I searched my email by called method  : search(SearchTerm term)
When i searched by param was FromStringTerm("n"), it always returned empty array. But if i searched by param was FromStringTerm("no") , it always returned array with some elements.
So did i call not correct or method  search(SearchTerm term) working not correct ?
Sorry. My Problem occured when i used IMAP GMAIL.
I founded solution that using GmailRawSearchTerm but i didn't find package com.sun.mail.gimap for Android.

**Comment by bshannon** [comment]
As described on the [Gmail issues page](https://javaee.github.io/javamail/Gmail), IMAP search in Gmail only searches entire words.

The existing com.sun.mail.gimap jar file should work fine on Android.
