### ISSUE TITLE
Correction method MimeUtility.decodeInnerWords

### ISSUE THREAD

**Issue by peterprvy** [javaee/javamail#305]
Sorry, my english is bad

If subject.sender.from.to, ...etc.  contains more encoded words like "=?utf-8?", method decodeWord does not work properly. Only one subword decode. 

Example, subject is:

=?utf-8?B?Tm92w6EgZnVua2Npb25hbGl0YSAtIE7DoXZyaCBuYSBuZcO6?=;=?utf-8?B?xI1pbm5vc8WlIGRvcnXEjW92YW5pYQ==?=

After decode:

Modul dlhodobého uchovávania na Ú;=?utf-8?B?UFZTIGRvIGtvbmNhIHJva2EgemFkYXJtbw==?=

after repairing the method,  before "return decodedWord;" (line 924):

	    int i = decodedWord.indexOf(";=?");
	    if (i > 0)
	    	decodedWord = decodedWord.substring(0,  i) + decodeWord(decodedWord.substring(i+1));

the method works properly, afted decode, subject is:

Modul dlhodobého uchovávania na ÚPVS do konca roka zadarmo

**Comment by peterprvy** [comment]
I'm sorry, I did not notice the property "mail.mime.decodetext.strict", but when I set it up

System.setProperty("mail.mime.decodetext.strict", "false");

after decode string contains semicolon

**Comment by bshannon** [comment]
The original text is encoded incorrectly.  Setting the strict property to false allows
it to be decode, but there's no way to know that the semicolon inserted between
the incorrectly encoded words is not part of the intended text and should be removed.

You need to report this problem to the owner of the mailer that created the
incorrectly encoded text.  That's where the fix needs to be applied.
