### ISSUE TITLE
StringIndexOutOfBoundsException when *.proxy.host contains a colon

### ISSUE THREAD

**Issue by koeberlue** [javaee/javamail#307]
When you put a colon `:` inside of your `*proxy.host` property, a `StringIndexOutOfBoundsException` is thrown. I checked the stacktrace and found the problem inside of the `com.sun.mail.util.SocketFetcher` class (about line 289):

    int i = proxyHost.indexOf(':');
    if (i >= 0) {
        proxyHost = proxyHost.substring(0, i);
        try {
            proxyPort = Integer.parseInt(proxyHost.substring(i + 1));
        } catch (NumberFormatException ex) {
             // ignore it
        }
    }

So the `proxyHost` is reduced up to it's `i`th position and directly after that the `i+1`th position is requested, which results in the aforementioned exception. This could probably be resolved by changing it to this:

    int i = proxyHost.indexOf(':');
    if (i >= 0) {
        try {
             proxyPort = Integer.parseInt(proxyHost.substring(i + 1));
        } catch (NumberFormatException ex) {
            // ignore it
        }
        proxyHost = proxyHost.substring(0, i);
    }

Since this is the first issue i created feel free to to give some feedback.

**Comment by bshannon** [comment]
Oops, yes, thank you for the bug report!
