### ISSUE TITLE
Content-Transfer-Encoding: 8bit" -> Unknown encoding: 8BIT"

### ISSUE THREAD

**Issue by morgancdip** [javaee/javamail#308]
i use version 1.6.0 on android
I received an email with an invalid encoding value and when I call the getContent function from part, there is an exception "Unknown encoding: 8BIT"". It is impossible to retrieve the contents of the message.
When I looked at the value of the encoding, I saw that there is a problem with a quotation mark : 8bit".
Is there a possibility to add additional processing on encoding processing when it is not valid? (here when we have 8bit" we deduce that it is 8bit)

**Comment by bshannon** [comment]
You can use the [MimeBodyPart.getRawInputStream](https://javaee.github.io/javamail/docs/api/javax/mail/internet/MimeBodyPart.html#getRawInputStream--) method to read the raw data without attempting to decode it.

And of course, if the message with this bad header is not spam, you should report this problem to the owner of the program that created the message.
