### ISSUE TITLE
Multipart Content-Transfer-Encoding trailing space

### ISSUE THREAD

**Issue by robscala** [javaee/javamail#309]
When reading an Imap email with a space after the Content-Transfer-Encoding of a part, that encoding is not recognized.  For example, the mail source contains:

     "Content-Transfer-Encoding: base64 "

In this case, the MimeUtility.decode() method throws an "Unknown encoding: base64 " exception.

It seems that this should be trimmed on parsing, or within the MimeUtility.decode() method.

This started when I switched from POP to IMAP, so this could be an IMAP-only problem.

I am using javamail 1.6.0 from maven.

**Comment by bshannon** [comment]
Most likely this is a bug in the IMAP server, which should parse the header and return a canonical value in the IMAP protocol response.  What IMAP server are you using?  What does the [JavaMail debug output](https://javaee.github.io/javamail/FAQ#debug) show?

**Comment by robscala** [comment]
The server is outlook.office365.com.  Here is the debug output (my added lines have a # prefix):

`DEBUG: setDebug: JavaMail version 1.6.0
DEBUG: getProvider() returning javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle]
DEBUG IMAPS: mail.imap.fetchsize: 2097152
DEBUG IMAPS: mail.imap.ignorebodystructuresize: false
DEBUG IMAPS: mail.imap.statuscachetimeout: 1000
DEBUG IMAPS: mail.imap.appendbuffersize: -1
DEBUG IMAPS: mail.imap.minidletime: 10
DEBUG IMAPS: closeFoldersOnStoreFailure
DEBUG IMAPS: trying to connect to host "outlook.office365.com", port 993, isSSL true
* OK The Microsoft Exchange IMAP4 service is ready. [QgBOADYAUABSADEAMgBDAEEAMAAwADQANAAuAG4AYQBtAHAAcgBkADEAMgAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]
A0 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
A0 OK CAPABILITY completed.
DEBUG IMAPS: AUTH: PLAIN
DEBUG IMAPS: AUTH: XOAUTH2
DEBUG IMAPS: protocolConnect login, host=outlook.office365.com, user=invoice@buyersedgepurchasing.com, password=<non-null>
DEBUG IMAPS: AUTHENTICATE PLAIN command trace suppressed
DEBUG IMAPS: AUTHENTICATE PLAIN command result: A1 OK AUTHENTICATE completed.
A2 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
A2 OK CAPABILITY completed.
DEBUG IMAPS: AUTH: PLAIN
DEBUG IMAPS: AUTH: XOAUTH2
DEBUG IMAPS: connection available -- size: 1
A3 SELECT "Problem Emails"
* 17 EXISTS
* 0 RECENT
* FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
* OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
* OK [UIDVALIDITY 181] UIDVALIDITY value
* OK [UIDNEXT 18] The next unique identifier value
A3 OK [READ-WRITE] SELECT completed.
A4 FETCH 1 (BODYSTRUCTURE)
* 1 FETCH (BODYSTRUCTURE (("text" "plain" ("charset" "iso-8859-1") NIL NIL "7bit" 0 0 NIL NIL NIL NIL)("application" "octet-stream" ("name" "citylineinv12012017.txt") NIL NIL "base64 " 6997492 NIL NIL NIL NIL) "mixed" ("boundary" "=_NextPart_00002BA8") NIL NIL))
A4 OK FETCH completed.
A5 FETCH 1 (ENVELOPE INTERNALDATE RFC822.SIZE)
* 1 FETCH (ENVELOPE ("Wed, 3 Jan 2018 14:29:22 +0000" "Invoice File for Chain Code:   2" ((NIL NIL "dglen" "CITYLINEFOODS.COM")) NIL NIL ((NIL NIL "invoice" "buyersedgepurchasing.com")) ((NIL NIL "ndonofriojr" "citylinefoods.com")) NIL NIL "<1cb48d6c-db45-49f5-98dd-73569ce94a89@CITMAIL01.cityline.local>") INTERNALDATE "03-Jan-2018 14:29:54 -0500" RFC822.SIZE 5128309)
A5 OK FETCH completed.
# Analyzing message:
#    Content Object: javax.mail.internet.MimeMultipart
#    Content Type:      multipart/mixed; boundary="=_NextPart_00002BA8"
#    File Name:       null
#    Encoding:        null
#    Subject:         Invoice File for Chain Code:   2
#    Description      null
#    Disposition:     null
# processMultiPart() - 2 part(s)
# Processing PART: 1 of 2:
#    Part class:  com.sun.mail.imap.IMAPBodyPart
#    File name:    null
#    Description:  null
#    ContentType:  text/plain; charset=iso-8859-1
#    Size:         0
#    Line Count:   0
#    Disposition:  null
# Calling part.getContent().
DEBUG IMAPS: IMAPProtocol noop
A6 NOOP
A6 OK NOOP completed.
A7 FETCH 1 (FLAGS)
* 1 FETCH (FLAGS (\Seen))
A7 OK FETCH completed.
# Found string content.
# Found string content.
# Processing PART: 2 of 2:
#    Part class:  com.sun.mail.imap.IMAPBodyPart
#    File name:    citylineinv12012017.txt
#    Description:  null
#    ContentType:  application/octet-stream; name=citylineinv12012017.txt
#    Size:         6997492
#    Line Count:   -1
#    Disposition:  null
# Calling part.getContent().
2018-03-04 16:13:18,902 [main] ERROR com.be.throwablehandling.ThrowableHandler :: Command-line tool error on signy.
java.io.IOException: Unknown encoding: base64 
	at javax.mail.internet.MimePartDataSource.getInputStream(MimePartDataSource.java:116) ~[javax.mail-1.6.0.jar:1.6.0]
	at javax.activation.DataSourceDataContentHandler.getContent(DataHandler.java:797) ~[na:1.8.0_152]
	at javax.activation.DataHandler.getContent(DataHandler.java:542) ~[na:1.8.0_152]
	at javax.mail.internet.MimeBodyPart.getContent(MimeBodyPart.java:678) ~[javax.mail-1.6.0.jar:1.6.0]
	at com.be.commandline.TestTools$TestMailCommand$AnalyzedMail.addAttachmentFromMultipart(TestTools.java:307) ~[classes/:na]
	at com.be.commandline.TestTools$TestMailCommand$AnalyzedMail.<init>(TestTools.java:228) ~[classes/:na]
	at com.be.commandline.TestTools$TestMailCommand$AnalyzedMail.<init>(TestTools.java:212) ~[classes/:na]
	at com.be.commandline.TestTools$TestMailCommand.run(TestTools.java:200) ~[classes/:na]
	at com.be.commandline.util.CommandLineTools.run(CommandLineTools.java:369) ~[classes/:na]
	at com.be.commandline.TestTools.main(TestTools.java:95) [classes/:na]
Caused by: javax.mail.MessagingException: Unknown encoding: base64 
	at javax.mail.internet.MimeUtility.decode(MimeUtility.java:392) ~[javax.mail-1.6.0.jar:1.6.0]
	at javax.mail.internet.MimePartDataSource.getInputStream(MimePartDataSource.java:109) ~[javax.mail-1.6.0.jar:1.6.0]
	... 9 common frames omitted
`

**Comment by robscala** [comment]
The server is outlook.office365.com.  The debug output is below.  My lines have a # prefix.

```
DEBUG: setDebug: JavaMail version 1.6.0
DEBUG: getProvider() returning javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle]
DEBUG IMAPS: mail.imap.fetchsize: 2097152
DEBUG IMAPS: mail.imap.ignorebodystructuresize: false
DEBUG IMAPS: mail.imap.statuscachetimeout: 1000
DEBUG IMAPS: mail.imap.appendbuffersize: -1
DEBUG IMAPS: mail.imap.minidletime: 10
DEBUG IMAPS: closeFoldersOnStoreFailure
DEBUG IMAPS: trying to connect to host "outlook.office365.com", port 993, isSSL true
* OK The Microsoft Exchange IMAP4 service is ready. [QgBOADYAUABSADEAMgBDAEEAMAAwADQANAAuAG4AYQBtAHAAcgBkADEAMgAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]
A0 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
A0 OK CAPABILITY completed.
DEBUG IMAPS: AUTH: PLAIN
DEBUG IMAPS: AUTH: XOAUTH2
DEBUG IMAPS: protocolConnect login, host=outlook.office365.com, user=invoice@buyersedgepurchasing.com, password=<non-null>
DEBUG IMAPS: AUTHENTICATE PLAIN command trace suppressed
DEBUG IMAPS: AUTHENTICATE PLAIN command result: A1 OK AUTHENTICATE completed.
A2 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
A2 OK CAPABILITY completed.
DEBUG IMAPS: AUTH: PLAIN
DEBUG IMAPS: AUTH: XOAUTH2
DEBUG IMAPS: connection available -- size: 1
A3 SELECT "Problem Emails"
* 17 EXISTS
* 0 RECENT
* FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
* OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)] Permanent flags
* OK [UIDVALIDITY 181] UIDVALIDITY value
* OK [UIDNEXT 18] The next unique identifier value
A3 OK [READ-WRITE] SELECT completed.
A4 FETCH 1 (BODYSTRUCTURE)
* 1 FETCH (BODYSTRUCTURE (("text" "plain" ("charset" "iso-8859-1") NIL NIL "7bit" 0 0 NIL NIL NIL NIL)("application" "octet-stream" ("name" "citylineinv12012017.txt") NIL NIL "base64 " 6997492 NIL NIL NIL NIL) "mixed" ("boundary" "=_NextPart_00002BA8") NIL NIL))
A4 OK FETCH completed.
A5 FETCH 1 (ENVELOPE INTERNALDATE RFC822.SIZE)
* 1 FETCH (ENVELOPE ("Wed, 3 Jan 2018 14:29:22 +0000" "Invoice File for Chain Code:   2" ((NIL NIL "dglen" "CITYLINEFOODS.COM")) NIL NIL ((NIL NIL "invoice" "buyersedgepurchasing.com")) ((NIL NIL "ndonofriojr" "citylinefoods.com")) NIL NIL "<1cb48d6c-db45-49f5-98dd-73569ce94a89@CITMAIL01.cityline.local>") INTERNALDATE "03-Jan-2018 14:29:54 -0500" RFC822.SIZE 5128309)
A5 OK FETCH completed.
# Analyzing message:
#    Content Object: javax.mail.internet.MimeMultipart
#    Content Type:      multipart/mixed; boundary="=_NextPart_00002BA8"
#    File Name:       null
#    Encoding:        null
#    Subject:         Invoice File for Chain Code:   2
#    Description      null
#    Disposition:     null
# processMultiPart() - 2 part(s)
# Processing PART: 1 of 2:
#    Part class:  com.sun.mail.imap.IMAPBodyPart
#    File name:    null
#    Description:  null
#    ContentType:  text/plain; charset=iso-8859-1
#    Size:         0
#    Line Count:   0
#    Disposition:  null
# Calling part.getContent().
DEBUG IMAPS: IMAPProtocol noop
A6 NOOP
A6 OK NOOP completed.
A7 FETCH 1 (FLAGS)
* 1 FETCH (FLAGS (\Seen))
A7 OK FETCH completed.
# Found string content.
# Found string content.
# Processing PART: 2 of 2:
#    Part class:  com.sun.mail.imap.IMAPBodyPart
#    File name:    citylineinv12012017.txt
#    Description:  null
#    ContentType:  application/octet-stream; name=citylineinv12012017.txt
#    Size:         6997492
#    Line Count:   -1
#    Disposition:  null
# Calling part.getContent().
2018-03-04 16:13:18,902 [main] ERROR com.be.throwablehandling.ThrowableHandler :: Command-line tool error on signy.
java.io.IOException: Unknown encoding: base64 
	at javax.mail.internet.MimePartDataSource.getInputStream(MimePartDataSource.java:116) ~[javax.mail-1.6.0.jar:1.6.0]
	at javax.activation.DataSourceDataContentHandler.getContent(DataHandler.java:797) ~[na:1.8.0_152]
	at javax.activation.DataHandler.getContent(DataHandler.java:542) ~[na:1.8.0_152]
	at javax.mail.internet.MimeBodyPart.getContent(MimeBodyPart.java:678) ~[javax.mail-1.6.0.jar:1.6.0]
	at com.be.commandline.TestTools$TestMailCommand$AnalyzedMail.addAttachmentFromMultipart(TestTools.java:307) ~[classes/:na]
	at com.be.commandline.TestTools$TestMailCommand$AnalyzedMail.<init>(TestTools.java:228) ~[classes/:na]
	at com.be.commandline.TestTools$TestMailCommand$AnalyzedMail.<init>(TestTools.java:212) ~[classes/:na]
	at com.be.commandline.TestTools$TestMailCommand.run(TestTools.java:200) ~[classes/:na]
	at com.be.commandline.util.CommandLineTools.run(CommandLineTools.java:369) ~[classes/:na]
	at com.be.commandline.TestTools.main(TestTools.java:95) [classes/:na]
Caused by: javax.mail.MessagingException: Unknown encoding: base64 
	at javax.mail.internet.MimeUtility.decode(MimeUtility.java:392) ~[javax.mail-1.6.0.jar:1.6.0]
	at javax.mail.internet.MimePartDataSource.getInputStream(MimePartDataSource.java:109) ~[javax.mail-1.6.0.jar:1.6.0]
	... 9 common frames omitted
```

**Comment by bshannon** [comment]
Yup, definitely a bug in the server, please report it to Microsoft.  Include the protocol trace in the bug report.  You can see where the server returns "base64 ".  I can consider adding a workaround in the next release of JavaMail.

**Comment by robscala** [comment]
Are you saying that the mail server should be rewriting the message body itself to correct errors?  My mail provider, AppRiver, believes that the message is valid.  And it parses fine with Outlook, Thunderbird, and even JavaMail (when using pop3).

**Comment by bshannon** [comment]
The mail server should parse the message, verify the syntax of the message, extract the values for the relevant fields, verify that the values are legitimate, and return those values in the IMAP protocol response.  When parsing the Content-Transfer-Encoding header to extract the value, the non-quoted spaces would be ignored and not included as part of the value since they're not semantically significant.

When JavaMail parses the message itself, it will do the above, but the point of the IMAP protocol is that the server does this parsing of the message so that the client doesn't have to.  The POP3 protocol just returns the raw message to the client, which has to parse it itself.

**Comment by robscala** [comment]
Thank you.  That makes perfect sense.  I've reported this to my provider, and hope to get Microsoft to address it.

It would be great if you could apply a workaround in the next release.
