### ISSUE TITLE
JavaMail 1.6+ crashes on Android API level 18

### ISSUE THREAD

**Issue by slowcar** [javaee/javamail#318]
It uses java.nio.charset.StandardCharsets in com.sun.mail.util.LineOutputStream which is only available since API level 19.
line 86
bytes = s.getBytes(StandardCharsets.UTF_8);
could be replaced with 
bytes = s.getBytes("UTF-8")

**Comment by bshannon** [comment]
As described on the [JavaMail for Android](https://javaee.github.io/javamail/Android) page, JavaMail requires API level 19, which corresponds to KitKat, the oldest supported Android release.

What sort of devices are you running in to that only support older releases?

**Comment by slowcar** [comment]
Sorry, i did not see the requirement. We have a Samsung Galaxy Nexus on 4.03 that we keep around to test on API 18, i don't think we actually have any customers that low.
I'll close the issue as API 19 is the oldest supported version as you stated.
