### ISSUE TITLE
Allow ignoring syntax validation by calling InternetAddress.parse() method by sending strict = false

### ISSUE THREAD

**Issue by kiziltas** [javaee/javamail#320]
The public method internally calls parse(String s, boolean strict, boolean parseHdr) with parseHdr set to false. This lead ignoreErrors to be set as false:

`boolean ignoreErrors = parseHdr && !strict;`

Please allow us to avoid syntax errors completely.

_First GitHub issue. Sorry for any mistake._

**Comment by bshannon** [comment]
The [InternetAddress.parseHeader](https://javaee.github.io/javamail/docs/api/javax/mail/internet/InternetAddress.html#parseHeader-java.lang.String-boolean-) method with strict set to false will ignore most,
hopefully all, syntax errors.  If you want to ignore errors, you should use that method.
If you find a syntax error it doesn't ignore, let me know.

Note that you can cause MimeMessage to use that method by setting the Session property
[`mail.mime.address.strict`](https://javaee.github.io/javamail/docs/api/javax/mail/internet/package-frame.html#mail.mime.address.strict) to false.
