### ISSUE TITLE
URLName.getURL() returns incorrect url.

### ISSUE THREAD

**Issue by baijnath-sag** [javaee/javamail#321]
Following code: 
`URLName urlName = new URLName("http://localhost:80/resource/test");`
`System.out.println(urlName.getURL());`
Prints:
http://localhost:80resource/test

Which is incorrect.

**Comment by bshannon** [comment]
Good catch!

URL expects the "file" component to include the character that separates it from the host:port,
but URLName does not.

I'll fix this for JavaMail 1.6.2.
