### ISSUE TITLE
Dots in local part of emails not handled properly

### ISSUE THREAD

**Issue by tweimer** [javaee/javamail#322]
Some invalid e-mail-addresses are incorrectly detected as valid, for example .test.@example.com or test..test@example.com

See [RFC3696](https://tools.ietf.org/html/rfc3696), 3. Restrictions on email addresses

>    Without quotes, local-parts may consist of any combination of
>    alphabetic characters, digits, or any of the special characters
>  
>       ! # $ % & ' * + - / = ?  ^ _ ` . { | } ~
It seems the following part is not checked in javamail, in **InternetAddress.parse()**:
>    period (".") may also appear, but may not be used to start or end the
>    local part, nor may two or more consecutive periods appear.

**Comment by bshannon** [comment]
As the javadocs say:

> If strict is true, many (but not all) of the RFC822 syntax rules are enforced.

Still, since this is checked for in domain names it seems reasonable to check for it
in local names as well, even though local names more often contain unexpected and
illegal names.
