### ISSUE TITLE
Bug crash: com.sun.mail.imap.IMAPSSLStore.finalize() timed out after 20 seconds

### ISSUE THREAD

**Issue by hungdtbk** [javaee/javamail#325]
First of all, I would like to thank you for providing a very wonderful library!
The library works well in most cases. However, after releasing the app on Playstore, I found a crash reported on the firebase, about 5% of users encounter this bug. Unfortunately I do not know how to reproduce this as well as to fix it. I hope you can help me guess the cause and fix it. Please see the stack trace log below.
Thanks so much!
----------------------------------------------
Fatal Exception: java.util.concurrent.TimeoutException
com.sun.mail.imap.IMAPSSLStore.finalize() timed out after 20 seconds
com.android.org.conscrypt.NativeCrypto.SSL_read (NativeCrypto.java)
com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read (OpenSSLSocketImpl.java:789)
com.sun.mail.util.TraceInputStream.read (SourceFile:126)
java.io.BufferedInputStream.fill (BufferedInputStream.java:235)
java.io.BufferedInputStream.read (BufferedInputStream.java:254)
com.sun.mail.iap.ResponseInputStream.readResponse (SourceFile:103)
com.sun.mail.iap.Response. (SourceFile:131)
com.sun.mail.imap.protocol.IMAPResponse. (SourceFile:60)
com.sun.mail.imap.protocol.IMAPProtocol.readResponse (SourceFile:407)
com.sun.mail.iap.Protocol.command (SourceFile:355)
com.sun.mail.imap.protocol.IMAPProtocol.logout (SourceFile:484)
com.sun.mail.imap.IMAPStore.close (SourceFile:1672)
com.sun.mail.imap.IMAPStore.finalize (SourceFile:1692)
java.lang.Daemons$FinalizerDaemon.doFinalize (Daemons.java:222)
java.lang.Daemons$FinalizerDaemon.run (Daemons.java:209)
java.lang.Thread.run (Thread.java:762)

**Comment by jmehrens** [comment]
Your code is not closing 'Folder' and 'Store' objects when you let them go out of scope.  Modify your code to ensure that close is being called.

**Comment by bshannon** [comment]
What version of JavaMail are you using?  Newer versions (>=1.5.6) will close the connection abruptly during finalize, without sending any commands or waiting for a response.  The property
[mail.imap.finalizecleanclose](https://javaee.github.io/javamail/docs/api/com/sun/mail/imap/package-summary.html#finalizecleanclose) controls this behavior.

**Comment by bshannon** [comment]
With no response from the submitter, I'm assuming this is an application bug and closing this bug report.
