### ISSUE TITLE
search with Unicode char throws BadCommandException with UTF8=ALLOW

### ISSUE THREAD

**Issue by a-en** [javaee/javamail#333]
It seems that there were some changes in between 1.5.6 and 1.6.0, which causes this issue. Starting from 1.6.0, when I try to search for email by subject, that contains special char (in my case it was **right single quotation mark** "\u2019"), I get exception:

`
Caused by: com.sun.mail.iap.BadCommandException: A4 BAD Could not parse command
	at com.sun.mail.iap.Protocol.handleResult(Protocol.java:399)
	at com.sun.mail.imap.protocol.IMAPProtocol.issueSearch(IMAPProtocol.java:2587)
	at com.sun.mail.imap.protocol.IMAPProtocol.search(IMAPProtocol.java:2511)
	at com.sun.mail.imap.protocol.IMAPProtocol.search(IMAPProtocol.java:2480)
	at com.sun.mail.imap.IMAPFolder.search(IMAPFolder.java:2373)
`

**Comment by bshannon** [comment]
Can you post the [JavaMail debug output](https://javaee.github.io/javamail/FAQ#debug) for both 1.5.6 and 1.6.0?
I get the same behavior in both cases.  Possibly this is a side effect of the UTF-8 support
added to JavaMail 1.6.0.

**Comment by a-en** [comment]
Hi Bill,
https://gist.github.com/a-en/ca96c668d5a6fbc4b530731b40194972 -- output for 1.5.6
https://gist.github.com/a-en/f6eae702c49f3bd4a52d0a16cfbf6979 -- output for 1.6.0

**Comment by bshannon** [comment]
Thanks for that.  I see that you're using Gmail.  It appears that Gmail is enforcing this
clause in RFC 6855:

     Once an IMAP client has enabled UTF-8 support with the "ENABLE
     UTF8=ACCEPT" command, it MUST NOT issue a "SEARCH" command that
     contains a charset specification.  If an IMAP server receives such a
     "SEARCH" command in that situation, it SHOULD reject the command with
     a "BAD" response (due to the conflicting charset labels).

And JavaMail is failing to honor the MUST NOT.  I've fixed that for JavaMail 1.6.2
and pushed out a 1.6.2-SNAPSHOT; please try it if you get a chance.

Thanks for reporting this bug!
